/*
Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
 */

/**
 * This program computes the sum of the even-valued terms in the Fibonacci
 * sequence below four million.
 *
 * @author Michael Mckee 2014
 */

public class FibonacciSum
{
  public static void main(String[] args)
  {
    int firstTerm = 1;
    int secondTerm = 2;
    int current = 0;

    int sum = 2;  // Start sum at 2 as our secondTerm starts at 2.

    while (current <= 4000000)
    {
      current = firstTerm + secondTerm;
      firstTerm = secondTerm;
      secondTerm = current;

      if (current % 2 == 0)
      {
        sum += current;
      }
    }

    System.out.println("The sum of the even-valued terms of the Fibonacci"
      + " sequence below four million is: " + sum);
  }
}
